sleep: 1

targets:
  - name: nimble test
    path: src
    commands:
      - nimble test
    extensions:
      - .nim
    once: true
  - name: echo test
    path: src
    commands:
      - echo unko
    exclude_extensions:
      - .md
    once: true
