targets:
  - name: go test
    path: .
    commands:
      - go test -v -cover ./...
    extensions:
      - go
  - name: echo test
    path: .
    commands:
      - echo unko
    extensions:
      - yml
